<?php

const TWITTER_API_KEY = 'TWITTER_API_KEY';
const TWITTER_API_SECRET = 'TWITTER_API_SECRET';
const TWITTER_SEARCH_USERNAME = '@exove';
const CACHE_ENABLED = false;
const CACHE_LIFETIME = 15;
const ETAG_ENABLED = false;
